### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for Inbound

### ISSUE THREAD

**Issue by Spp595** [iwatkot/py3xui#41]
Today my script stopped working and it won't start anymore. I didn't change anything in it. pydantic writes an error when I want to get the inbounds list
```

Traceback (most recent call last):
  File "/home/sp595/code/app/xui_api.py", line 138, in <module>
    inbounds = (api.inbound.get_list())
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sp595/code/.venv/lib/python3.12/site-packages/py3xui/api/api_inbound.py", line 69, in get_list
    inbounds = [Inbound.model_validate(data) for data in inbounds_json]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sp595/code/.venv/lib/python3.12/site-packages/pydantic/main.py", line 596, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Inbound
settings.clients.3.reset
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/int_type
```

**Comment by Spp595** [comment]
3x-ui 2.48
Python 3.12.7
py3xui==0.3.0
pydantic==2.9.2
OS = arch and debian 12

**Comment by Spp595** [comment]
the code i am trying to run
```
api = Api.from_env()
api.login()
inbounds = str(api.inbound.get_list())
print(inbounds)

```

**Comment by iwatkot** [comment]
@Spp595, pydantic fails to validate the JSON because the reset field is None, while it should be an integer.
You may try to change it in the model and you're welcome to create a PR with this update.

Here: https://github.com/iwatkot/py3xui/blob/main/py3xui/client/client.py#L68

Should be int | None with default None, but needs checks and testing.

**Comment by Spp595** [comment]
created

**Comment by Spp595** [comment]
after this change the error really disappeared

**Comment by iwatkot** [comment]
@Spp595, merged and released.

Thanks for the PR.
